src/Web/Controllers/BasketController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Interfaces;
using Web.ViewModels;

namespace Web.Controllers
{
    //todo: web > basketviewmodelservice > getcreatebasket
    //todo: appcore > basketservice > additemtobasket
    public class BasketController : Controller
    {
        private readonly IBasketViewModelService _basketViewModelService;
        private readonly IBasketService _basketService;
        private readonly IOrderService _orderService;

        public BasketController(IBasketViewModelService basketViewModelService, IBasketService basketService, IOrderService orderService)
        {
            _basketViewModelService = basketViewModelService;
            _basketService = basketService;
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _basketViewModelService.GetBasketViewModel());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToBasket(int productId, int quantity)
        {
            // application core projesinde BasketService:IBasketService
            //AddItemToBasket(int basketId, int catologId,int quantity)
            //sepette varsa adedini güncelle yoksa ekle
            //sepetteki öğe sayısını döndür

            var basketId = await _basketViewModelService.GetOrCreateBasketIdAsync();
            await _basketService.AddItemToBasket(basketId, productId, quantity);
            int basketItemsCount = await _basketService.BasketItemsCount(basketId);

            return Json(await _basketViewModelService.GetBasketItemsCountViewModel(basketId));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveBasketItem(int basketItemId)
        {
            var basketId = await _basketViewModelService.GetOrCreateBasketIdAsync();
            await _basketService.DeleteBasketItem(basketId, basketItemId);
            return PartialView("_BasketPartial", await _basketViewModelService.GetBasketViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBasketItem(int basketItemId, int quantity)
        {
            if (quantity < 1) return BadRequest("The quantity cannot be less than 1.");
            var basketId = await _basketViewModelService.GetOrCreateBasketIdAsync();
            await _basketService.UpdateBasketItem(basketId, basketItemId, quantity);
            return PartialView("_BasketPartial", await _basketViewModelService.GetBasketViewModel());
        }

        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            var vm = new CheckoutViewModel()
            {
                BasketItems = await _basketViewModelService.GetBasketItems()

            };
            return View(vm);
        }

        [Authorize, HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(CheckoutViewModel model)
        {
            if (ModelState.IsValid)
            {
                int basketId = await _basketViewModelService.GetOrCreateBasketIdAsync();

                //Process th payment
                //place the order
                var adress = new Address()
                {
                    City = model.City,
                    Country = model.Country,
                    Street = model.Street,
                    State = model.State,
                    ZipCode = model.ZipCode
                };
                await _orderService.CreateOrderAsync(basketId, adress);
                //delete the basket
                await _basketService.DeleteBasketAsync(basketId);

                return RedirectToAction("Success");
            }
            model.BasketItems = await _basketViewModelService.GetBasketItems();
            return View(model);
        }

        public IActionResult Success()
        {
            return View();
        }
    }
}

src/Web/Controllers/HomeController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Web.Interfaces;
using Web.Models;
using Web.ViewModels;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHomeViewModelService _homeViewModelService;


        public HomeController(ILogger<HomeController> logger, IHomeViewModelService homeViewModelService)
        {
            _logger = logger;
            _homeViewModelService = homeViewModelService;

        }

        public async Task<IActionResult> Index(HomeIndexViewModel vm, int page = 1)
        {
            return View(await _homeViewModelService.GetHomeIndexViewModel(vm.CategoryId, vm.AuthorId, page, Constants.ITEMS_PER_PAGE));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Web/Views/Home/Index.cshtml
@model HomeIndexViewModel
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Xsrf
@{
    ViewData["Title"] = "Home Page";
    var token = Xsrf.GetAndStoreTokens(Context).RequestToken;
}
<form class="form-inline py-3">
    <label class="mr-1">Category: </label>
    <select asp-for="CategoryId" asp-items="Model.Categories" class="form-control mr-0 mr-sm-2"></select>
    <label class="mr-1 mt-2 mt-sm-0">Author: </label>
    <select asp-for="AuthorId" asp-items="Model.Authors" class="form-control"></select>
    @*<button class="btn btn-primary">Filtrele</button>*@

</form>
<div class="row mx-md-n2">
    @foreach (var product in Model.Products)
    {

        <div class="col-sm-3 px-md-2 mb-4 d-flex flex-column align-items-center ">
            <div class="product-image-wrapper">
                <img src="~/img/@product.PictureUri" class="product-image" />
            </div>
            <div class="product-name">
                <h5>@product.Name</h5>
            </div>
            <div class="author-name">
                @product.AuthorName
            </div>
            <div class="product-price">
                <p>@product.Price.ToString("c2")</p>
            </div>
            <a href="#" class="btn btn-success btn-sm mt-auto" data-add-to-basket="@product.Id"><i class="fas fa-cart-plus"></i>Add to Basket</a>
        </div>
    }
</div>

<partial name="_PaginationPartial" model="Model.PaginationInfo" />

@section scripts{
    <script>
        $("#CategoryId,#AuthorId").change(function () {
            $(this).closest("form").submit();
        });

        $("[data-add-to-basket]").click(function (event) {
            event.preventDefault();
            var productId = $(this).data('add-to-basket');
            $.ajax({
                type: "POST",
                url: "@Url.Action("AddToBasket", "Basket")",
                headers: {
                    RequestVerificationToken:"@token",
                },
                data: {
                    productId: productId,
                    quantity: 1
                },
                success: function (data) {
                    $("#navBasketItemsCount").text(data.basketItemsCount);
                    toastr.success("The item has been added to the basket.")
                }
            });
        });
    </script>

}